import { IndiaState, IndiaDistrict, Institution } from '../../types/institution';

export const INDIA_STATES: IndiaState[] = [
  { id: 'AN', name: 'Andaman and Nicobar Islands', type: 'UT', code: 'AN', totalDistricts: 3 },
  { id: 'AP', name: 'Andhra Pradesh', type: 'STATE', code: 'AP', totalDistricts: 26 },
  { id: 'AR', name: 'Arunachal Pradesh', type: 'STATE', code: 'AR', totalDistricts: 26 },
  { id: 'AS', name: 'Assam', type: 'STATE', code: 'AS', totalDistricts: 31 },
  { id: 'BR', name: 'Bihar', type: 'STATE', code: 'BR', totalDistricts: 38 },
  { id: 'CH', name: 'Chandigarh', type: 'UT', code: 'CH', totalDistricts: 1 },
  { id: 'CT', name: 'Chhattisgarh', type: 'STATE', code: 'CT', totalDistricts: 33 },
  { id: 'DH', name: 'Dadra and Nagar Haveli and Daman and Diu', type: 'UT', code: 'DH', totalDistricts: 3 },
  { id: 'DL', name: 'Delhi (NCT)', type: 'UT', code: 'DL', totalDistricts: 11 },
  { id: 'GA', name: 'Goa', type: 'STATE', code: 'GA', totalDistricts: 2 },
  { id: 'GJ', name: 'Gujarat', type: 'STATE', code: 'GJ', totalDistricts: 33 },
  { id: 'HR', name: 'Haryana', type: 'STATE', code: 'HR', totalDistricts: 22 },
  { id: 'HP', name: 'Himachal Pradesh', type: 'STATE', code: 'HP', totalDistricts: 12 },
  { id: 'JK', name: 'Jammu and Kashmir', type: 'UT', code: 'JK', totalDistricts: 20 },
  { id: 'JH', name: 'Jharkhand', type: 'STATE', code: 'JH', totalDistricts: 24 },
  { id: 'KA', name: 'Karnataka', type: 'STATE', code: 'KA', totalDistricts: 31 },
  { id: 'KL', name: 'Kerala', type: 'STATE', code: 'KL', totalDistricts: 14 },
  { id: 'LA', name: 'Ladakh', type: 'UT', code: 'LA', totalDistricts: 2 },
  { id: 'LD', name: 'Lakshadweep', type: 'UT', code: 'LD', totalDistricts: 1 },
  { id: 'MP', name: 'Madhya Pradesh', type: 'STATE', code: 'MP', totalDistricts: 55 },
  { id: 'MH', name: 'Maharashtra', type: 'STATE', code: 'MH', totalDistricts: 36 },
  { id: 'MN', name: 'Manipur', type: 'STATE', code: 'MN', totalDistricts: 16 },
  { id: 'ML', name: 'Meghalaya', type: 'STATE', code: 'ML', totalDistricts: 12 },
  { id: 'MZ', name: 'Mizoram', type: 'STATE', code: 'MZ', totalDistricts: 11 },
  { id: 'NL', name: 'Nagaland', type: 'STATE', code: 'NL', totalDistricts: 16 },
  { id: 'OD', name: 'Odisha', type: 'STATE', code: 'OD', totalDistricts: 30 },
  { id: 'PY', name: 'Puducherry', type: 'UT', code: 'PY', totalDistricts: 4 },
  { id: 'PB', name: 'Punjab', type: 'STATE', code: 'PB', totalDistricts: 23 },
  { id: 'RJ', name: 'Rajasthan', type: 'STATE', code: 'RJ', totalDistricts: 50 },
  { id: 'SK', name: 'Sikkim', type: 'STATE', code: 'SK', totalDistricts: 6 },
  { id: 'TN', name: 'Tamil Nadu', type: 'STATE', code: 'TN', totalDistricts: 38 },
  { id: 'TG', name: 'Telangana', type: 'STATE', code: 'TG', totalDistricts: 33 },
  { id: 'TR', name: 'Tripura', type: 'STATE', code: 'TR', totalDistricts: 8 },
  { id: 'UP', name: 'Uttar Pradesh', type: 'STATE', code: 'UP', totalDistricts: 75 },
  { id: 'UK', name: 'Uttarakhand', type: 'STATE', code: 'UK', totalDistricts: 13 },
  { id: 'WB', name: 'West Bengal', type: 'STATE', code: 'WB', totalDistricts: 23 }
];

export const INDIA_DISTRICTS: Record<string, IndiaDistrict[]> = {
  TN: [
    { id: 'TN-CHE', stateId: 'TN', name: 'Chennai', headquarters: 'Chennai' },
    { id: 'TN-COI', stateId: 'TN', name: 'Coimbatore', headquarters: 'Coimbatore' },
    { id: 'TN-MAD', stateId: 'TN', name: 'Madurai', headquarters: 'Madurai' },
    { id: 'TN-TRI', stateId: 'TN', name: 'Tiruchirappalli', headquarters: 'Tiruchirappalli' },
    { id: 'TN-SAL', stateId: 'TN', name: 'Salem', headquarters: 'Salem' },
    { id: 'TN-KAN', stateId: 'TN', name: 'Kanchipuram', headquarters: 'Kanchipuram' },
    { id: 'TN-CHE2', stateId: 'TN', name: 'Chengalpattu', headquarters: 'Chengalpattu' },
    { id: 'TN-VEL', stateId: 'TN', name: 'Vellore', headquarters: 'Vellore' },
    { id: 'TN-ERO', stateId: 'TN', name: 'Erode', headquarters: 'Erode' },
    { id: 'TN-TIR', stateId: 'TN', name: 'Tirunelveli', headquarters: 'Tirunelveli' },
    { id: 'TN-THA', stateId: 'TN', name: 'Thanjavur', headquarters: 'Thanjavur' },
    { id: 'TN-TIR2', stateId: 'TN', name: 'Tiruppur', headquarters: 'Tiruppur' },
    { id: 'TN-DIN', stateId: 'TN', name: 'Dindigul', headquarters: 'Dindigul' },
    { id: 'TN-CUD', stateId: 'TN', name: 'Cuddalore', headquarters: 'Cuddalore' },
    { id: 'TN-KRU', stateId: 'TN', name: 'Karur', headquarters: 'Karur' },
    { id: 'TN-KRI', stateId: 'TN', name: 'Krishnagiri', headquarters: 'Krishnagiri' },
    { id: 'TN-KAN2', stateId: 'TN', name: 'Kanyakumari', headquarters: 'Nagercoil' },
    { id: 'TN-NAM', stateId: 'TN', name: 'Namakkal', headquarters: 'Namakkal' },
    { id: 'TN-NIL', stateId: 'TN', name: 'Nilgiris', headquarters: 'Udhagamandalam' },
    { id: 'TN-THI', stateId: 'TN', name: 'Thiruvallur', headquarters: 'Thiruvallur' }
  ],
  KA: [
    { id: 'KA-BLRU', stateId: 'KA', name: 'Bengaluru Urban', headquarters: 'Bengaluru' },
    { id: 'KA-BLRR', stateId: 'KA', name: 'Bengaluru Rural', headquarters: 'Bengaluru' },
    { id: 'KA-MYS', stateId: 'KA', name: 'Mysuru', headquarters: 'Mysuru' },
    { id: 'KA-DKA', stateId: 'KA', name: 'Dakshina Kannada (Mangaluru)', headquarters: 'Mangaluru' },
    { id: 'KA-UDU', stateId: 'KA', name: 'Udupi', headquarters: 'Udupi' },
    { id: 'KA-DHA', stateId: 'KA', name: 'Dharwad (Hubballi)', headquarters: 'Dharwad' },
    { id: 'KA-BEL', stateId: 'KA', name: 'Belagavi', headquarters: 'Belagavi' },
    { id: 'KA-TUM', stateId: 'KA', name: 'Tumakuru', headquarters: 'Tumakuru' },
    { id: 'KA-SHI', stateId: 'KA', name: 'Shivamogga', headquarters: 'Shivamogga' },
    { id: 'KA-KAL', stateId: 'KA', name: 'Kalaburagi', headquarters: 'Kalaburagi' }
  ],
  MH: [
    { id: 'MH-MUM', stateId: 'MH', name: 'Mumbai City', headquarters: 'Mumbai' },
    { id: 'MH-MSU', stateId: 'MH', name: 'Mumbai Suburban', headquarters: 'Bandra' },
    { id: 'MH-PUN', stateId: 'MH', name: 'Pune', headquarters: 'Pune' },
    { id: 'MH-NAG', stateId: 'MH', name: 'Nagpur', headquarters: 'Nagpur' },
    { id: 'MH-NAS', stateId: 'MH', name: 'Nashik', headquarters: 'Nashik' },
    { id: 'MH-THA', stateId: 'MH', name: 'Thane', headquarters: 'Thane' },
    { id: 'MH-AUR', stateId: 'MH', name: 'Chhatrapati Sambhajinagar (Aurangabad)', headquarters: 'Chhatrapati Sambhajinagar' },
    { id: 'MH-KOL', stateId: 'MH', name: 'Kolhapur', headquarters: 'Kolhapur' },
    { id: 'MH-SOL', stateId: 'MH', name: 'Solapur', headquarters: 'Solapur' },
    { id: 'MH-AMR', stateId: 'MH', name: 'Amravati', headquarters: 'Amravati' }
  ],
  DL: [
    { id: 'DL-NDL', stateId: 'DL', name: 'New Delhi', headquarters: 'New Delhi' },
    { id: 'DL-CDL', stateId: 'DL', name: 'Central Delhi', headquarters: 'Central Delhi' },
    { id: 'DL-SDL', stateId: 'DL', name: 'South Delhi', headquarters: 'South Delhi' },
    { id: 'DL-SWD', stateId: 'DL', name: 'South West Delhi', headquarters: 'South West Delhi' },
    { id: 'DL-ND2', stateId: 'DL', name: 'North Delhi', headquarters: 'North Delhi' },
    { id: 'DL-EDL', stateId: 'DL', name: 'East Delhi', headquarters: 'East Delhi' }
  ],
  TG: [
    { id: 'TG-HYD', stateId: 'TG', name: 'Hyderabad', headquarters: 'Hyderabad' },
    { id: 'TG-MED', stateId: 'TG', name: 'Medchal-Malkajgiri', headquarters: 'Shamirpet' },
    { id: 'TG-RAN', stateId: 'TG', name: 'Rangareddy', headquarters: 'Shamshabad' },
    { id: 'TG-HAN', stateId: 'TG', name: 'Hanamkonda (Warangal)', headquarters: 'Hanamkonda' },
    { id: 'TG-SAN', stateId: 'TG', name: 'Sangareddy', headquarters: 'Sangareddy' },
    { id: 'TG-KAR', stateId: 'TG', name: 'Karimnagar', headquarters: 'Karimnagar' },
    { id: 'TG-KHA', stateId: 'TG', name: 'Khammam', headquarters: 'Khammam' }
  ],
  AP: [
    { id: 'AP-VSP', stateId: 'AP', name: 'Visakhapatnam', headquarters: 'Visakhapatnam' },
    { id: 'AP-NTR', stateId: 'AP', name: 'NTR (Vijayawada)', headquarters: 'Vijayawada' },
    { id: 'AP-GNT', stateId: 'AP', name: 'Guntur', headquarters: 'Guntur' },
    { id: 'AP-CTR', stateId: 'AP', name: 'Chittoor', headquarters: 'Chittoor' },
    { id: 'AP-TPT', stateId: 'AP', name: 'Tirupati', headquarters: 'Tirupati' },
    { id: 'AP-KUR', stateId: 'AP', name: 'Kurnool', headquarters: 'Kurnool' },
    { id: 'AP-KRI', stateId: 'AP', name: 'Krishna', headquarters: 'Machilipatnam' },
    { id: 'AP-EGO', stateId: 'AP', name: 'East Godavari', headquarters: 'Rajahmundry' }
  ],
  KL: [
    { id: 'KL-TVM', stateId: 'KL', name: 'Thiruvananthapuram', headquarters: 'Thiruvananthapuram' },
    { id: 'KL-EKM', stateId: 'KL', name: 'Ernakulam (Kochi)', headquarters: 'Kochi' },
    { id: 'KL-KOZ', stateId: 'KL', name: 'Kozhikode', headquarters: 'Kozhikode' },
    { id: 'KL-TSR', stateId: 'KL', name: 'Thrissur', headquarters: 'Thrissur' },
    { id: 'KL-KOT', stateId: 'KL', name: 'Kottayam', headquarters: 'Kottayam' },
    { id: 'KL-PAL', stateId: 'KL', name: 'Palakkad', headquarters: 'Palakkad' },
    { id: 'KL-KNR', stateId: 'KL', name: 'Kannur', headquarters: 'Kannur' }
  ],
  WB: [
    { id: 'WB-KOL', stateId: 'WB', name: 'Kolkata', headquarters: 'Kolkata' },
    { id: 'WB-HGY', stateId: 'WB', name: 'Hooghly', headquarters: 'Chinsurah' },
    { id: 'WB-HOW', stateId: 'WB', name: 'Howrah', headquarters: 'Howrah' },
    { id: 'WB-N24', stateId: 'WB', name: 'North 24 Parganas', headquarters: 'Barasat' },
    { id: 'WB-S24', stateId: 'WB', name: 'South 24 Parganas', headquarters: 'Alipore' },
    { id: 'WB-PAS', stateId: 'WB', name: 'Paschim Bardhaman (Durgapur/Asansol)', headquarters: 'Asansol' },
    { id: 'WB-DAR', stateId: 'WB', name: 'Darjeeling', headquarters: 'Darjeeling' }
  ],
  GJ: [
    { id: 'GJ-AHM', stateId: 'GJ', name: 'Ahmedabad', headquarters: 'Ahmedabad' },
    { id: 'GJ-GAN', stateId: 'GJ', name: 'Gandhinagar', headquarters: 'Gandhinagar' },
    { id: 'GJ-SUR', stateId: 'GJ', name: 'Surat', headquarters: 'Surat' },
    { id: 'GJ-VAD', stateId: 'GJ', name: 'Vadodara', headquarters: 'Vadodara' },
    { id: 'GJ-RAJ', stateId: 'GJ', name: 'Rajkot', headquarters: 'Rajkot' }
  ],
  UP: [
    { id: 'UP-LKO', stateId: 'UP', name: 'Lucknow', headquarters: 'Lucknow' },
    { id: 'UP-KAN', stateId: 'UP', name: 'Kanpur Nagar', headquarters: 'Kanpur' },
    { id: 'UP-GBN', stateId: 'UP', name: 'Gautam Buddha Nagar (Noida)', headquarters: 'Greater Noida' },
    { id: 'UP-GHA', stateId: 'UP', name: 'Ghaziabad', headquarters: 'Ghaziabad' },
    { id: 'UP-VAR', stateId: 'UP', name: 'Varanasi', headquarters: 'Varanasi' },
    { id: 'UP-PRAY', stateId: 'UP', name: 'Prayagraj (Allahabad)', headquarters: 'Prayagraj' },
    { id: 'UP-AGR', stateId: 'UP', name: 'Agra', headquarters: 'Agra' },
    { id: 'UP-ALI', stateId: 'UP', name: 'Aligarh', headquarters: 'Aligarh' },
    { id: 'UP-MEE', stateId: 'UP', name: 'Meerut', headquarters: 'Meerut' }
  ],
  RJ: [
    { id: 'RJ-JAI', stateId: 'RJ', name: 'Jaipur', headquarters: 'Jaipur' },
    { id: 'RJ-JOD', stateId: 'RJ', name: 'Jodhpur', headquarters: 'Jodhpur' },
    { id: 'RJ-UDA', stateId: 'RJ', name: 'Udaipur', headquarters: 'Udaipur' },
    { id: 'RJ-KOT', stateId: 'RJ', name: 'Kota', headquarters: 'Kota' },
    { id: 'RJ-AJM', stateId: 'RJ', name: 'Ajmer', headquarters: 'Ajmer' },
    { id: 'RJ-BIK', stateId: 'RJ', name: 'Bikaner', headquarters: 'Bikaner' }
  ],
  PB: [
    { id: 'PB-SAS', stateId: 'PB', name: 'SAS Nagar (Mohali)', headquarters: 'Mohali' },
    { id: 'PB-LUD', stateId: 'PB', name: 'Ludhiana', headquarters: 'Ludhiana' },
    { id: 'PB-AMR', stateId: 'PB', name: 'Amritsar', headquarters: 'Amritsar' },
    { id: 'PB-JAL', stateId: 'PB', name: 'Jalandhar', headquarters: 'Jalandhar' },
    { id: 'PB-PAT', stateId: 'PB', name: 'Patiala', headquarters: 'Patiala' },
    { id: 'PB-RUP', stateId: 'PB', name: 'Rupnagar (Ropar)', headquarters: 'Rupnagar' }
  ],
  CH: [
    { id: 'CH-CHD', stateId: 'CH', name: 'Chandigarh', headquarters: 'Chandigarh' }
  ],
  PY: [
    { id: 'PY-PUD', stateId: 'PY', name: 'Puducherry', headquarters: 'Puducherry' },
    { id: 'PY-KAR', stateId: 'PY', name: 'Karaikal', headquarters: 'Karaikal' }
  ],
  OD: [
    { id: 'OD-KHO', stateId: 'OD', name: 'Khurda (Bhubaneswar)', headquarters: 'Bhubaneswar' },
    { id: 'OD-CUT', stateId: 'OD', name: 'Cuttack', headquarters: 'Cuttack' },
    { id: 'OD-SUN', stateId: 'OD', name: 'Sundargarh (Rourkela)', headquarters: 'Rourkela' },
    { id: 'OD-SAM', stateId: 'OD', name: 'Sambalpur', headquarters: 'Sambalpur' }
  ],
  MP: [
    { id: 'MP-BHO', stateId: 'MP', name: 'Bhopal', headquarters: 'Bhopal' },
    { id: 'MP-IND', stateId: 'MP', name: 'Indore', headquarters: 'Indore' },
    { id: 'MP-JAB', stateId: 'MP', name: 'Jabalpur', headquarters: 'Jabalpur' },
    { id: 'MP-GWA', stateId: 'MP', name: 'Gwalior', headquarters: 'Gwalior' }
  ],
  BR: [
    { id: 'BR-PAT', stateId: 'BR', name: 'Patna', headquarters: 'Patna' },
    { id: 'BR-GAY', stateId: 'BR', name: 'Gaya', headquarters: 'Gaya' },
    { id: 'BR-BHA', stateId: 'BR', name: 'Bhagalpur', headquarters: 'Bhagalpur' },
    { id: 'BR-MUZ', stateId: 'BR', name: 'Muzaffarpur', headquarters: 'Muzaffarpur' }
  ],
  HR: [
    { id: 'HR-GUR', stateId: 'HR', name: 'Gurugram', headquarters: 'Gurugram' },
    { id: 'HR-FAR', stateId: 'HR', name: 'Faridabad', headquarters: 'Faridabad' },
    { id: 'HR-KUR', stateId: 'HR', name: 'Kurukshetra', headquarters: 'Kurukshetra' },
    { id: 'HR-SON', stateId: 'HR', name: 'Sonipat', headquarters: 'Sonipat' },
    { id: 'HR-PAN', stateId: 'HR', name: 'Panchkula', headquarters: 'Panchkula' },
    { id: 'HR-ROH', stateId: 'HR', name: 'Rohtak', headquarters: 'Rohtak' },
    { id: 'HR-HIS', stateId: 'HR', name: 'Hisar', headquarters: 'Hisar' }
  ],
  UK: [
    { id: 'UK-DEH', stateId: 'UK', name: 'Dehradun', headquarters: 'Dehradun' },
    { id: 'UK-HAR', stateId: 'UK', name: 'Haridwar (Roorkee)', headquarters: 'Haridwar' },
    { id: 'UK-NAI', stateId: 'UK', name: 'Nainital', headquarters: 'Nainital' },
    { id: 'UK-PAU', stateId: 'UK', name: 'Pauri Garhwal', headquarters: 'Pauri' }
  ],
  JH: [
    { id: 'JH-RAN', stateId: 'JH', name: 'Ranchi', headquarters: 'Ranchi' },
    { id: 'JH-EAS', stateId: 'JH', name: 'East Singhbhum (Jamshedpur)', headquarters: 'Jamshedpur' },
    { id: 'JH-DHA', stateId: 'JH', name: 'Dhanbad', headquarters: 'Dhanbad' },
    { id: 'JH-BOK', stateId: 'JH', name: 'Bokaro', headquarters: 'Bokaro' }
  ],
  AS: [
    { id: 'AS-KAM', stateId: 'AS', name: 'Kamrup Metropolitan (Guwahati)', headquarters: 'Guwahati' },
    { id: 'AS-JOR', stateId: 'AS', name: 'Jorhat', headquarters: 'Jorhat' },
    { id: 'AS-DIB', stateId: 'AS', name: 'Dibrugarh', headquarters: 'Dibrugarh' },
    { id: 'AS-SIL', stateId: 'AS', name: 'Cachar (Silchar)', headquarters: 'Silchar' }
  ],
  GA: [
    { id: 'GA-NGA', stateId: 'GA', name: 'North Goa', headquarters: 'Panaji' },
    { id: 'GA-SGA', stateId: 'GA', name: 'South Goa', headquarters: 'Margao' }
  ],
  HP: [
    { id: 'HP-SHI', stateId: 'HP', name: 'Shimla', headquarters: 'Shimla' },
    { id: 'HP-MAN', stateId: 'HP', name: 'Mandi', headquarters: 'Mandi' },
    { id: 'HP-SOL', stateId: 'HP', name: 'Solan', headquarters: 'Solan' },
    { id: 'HP-HAM', stateId: 'HP', name: 'Hamirpur', headquarters: 'Hamirpur' }
  ],
  JK: [
    { id: 'JK-SRI', stateId: 'JK', name: 'Srinagar', headquarters: 'Srinagar' },
    { id: 'JK-JAM', stateId: 'JK', name: 'Jammu', headquarters: 'Jammu' }
  ]
};

export const INITIAL_INSTITUTIONS: Institution[] = [
  // Tamil Nadu
  {
    id: 'inst-psg-tech',
    aisheCode: 'C-41046',
    name: 'PSG College of Technology',
    shortName: 'PSG Tech',
    slug: 'psg-college-of-technology',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'GOVT_AIDED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-COI',
    districtName: 'Coimbatore',
    city: 'Coimbatore',
    address: 'Avinashi Road, Peelamedu, Coimbatore - 641004',
    pincode: '641004',
    website: 'https://www.psgtech.edu',
    email: 'principal@psgtech.edu',
    establishedYear: 1951,
    accreditation: 'NAAC A+ Grade / NBA',
    affiliatingUniversity: 'Anna University, Chennai',
    nirfRank: 63,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['PSG Tech', 'PSG', 'PSG College', 'PSGCT', 'PSG Coimbatore', 'Peelamedu Engineering'],
    studentCount: 8500,
    mentorCount: 5,
    eventCount: 24,
    ambassadorCount: 3,
    tags: ['Engineering', 'Autonomous', 'Govt Aided', 'Top Ranked', 'Coimbatore'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iit-madras',
    aisheCode: 'U-0456',
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    slug: 'iit-madras',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-CHE',
    districtName: 'Chennai',
    city: 'Chennai',
    address: 'IIT P.O., Chennai - 600036',
    pincode: '600036',
    website: 'https://www.iitm.ac.in',
    email: 'director@iitm.ac.in',
    establishedYear: 1959,
    accreditation: 'Institute of Eminence (IoE)',
    nirfRank: 1,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Madras', 'IITM', 'IIT Chennai', 'Indian Institute of Technology Madras', 'Shaastra', 'Saarang'],
    studentCount: 11000,
    mentorCount: 8,
    eventCount: 42,
    ambassadorCount: 5,
    tags: ['IIT', 'Central Govt', 'NIRF Rank 1', 'Engineering', 'Research'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-anna-univ',
    aisheCode: 'U-0439',
    name: 'Anna University, Chennai (CEG Campus)',
    shortName: 'Anna University (CEG)',
    slug: 'anna-university-ceg',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-CHE',
    districtName: 'Chennai',
    city: 'Chennai',
    address: 'Sardar Patel Road, Guindy, Chennai - 600025',
    pincode: '600025',
    website: 'https://www.annauniv.edu',
    email: 'registrar@annauniv.edu',
    establishedYear: 1794,
    accreditation: 'NAAC A++ Grade',
    nirfRank: 13,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['Anna University', 'CEG Guindy', 'College of Engineering Guindy', 'AU Chennai', 'Anna Univ', 'Kurukshetra CEG'],
    studentCount: 14000,
    mentorCount: 6,
    eventCount: 35,
    ambassadorCount: 4,
    tags: ['State University', 'CEG', 'Guindy', 'Premier Engineering', 'Chennai'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-nit-trichy',
    aisheCode: 'U-0467',
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    slug: 'nit-trichy',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-TRI',
    districtName: 'Tiruchirappalli',
    city: 'Tiruchirappalli',
    address: 'Tanjore Main Road, National Highway 67, Tiruchirappalli - 620015',
    pincode: '620015',
    website: 'https://www.nitt.edu',
    email: 'director@nitt.edu',
    establishedYear: 1964,
    accreditation: 'NAAC A++ Grade / Institute of National Importance',
    nirfRank: 9,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NIT Trichy', 'NITT', 'REC Trichy', 'NIT Tiruchirappalli', 'Pragyan', 'Festember'],
    studentCount: 6800,
    mentorCount: 6,
    eventCount: 28,
    ambassadorCount: 4,
    tags: ['NIT', 'Central Govt', 'Top 10 Engineering', 'Trichy'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-cit-coimbatore',
    aisheCode: 'C-41050',
    name: 'Coimbatore Institute of Technology',
    shortName: 'CIT Coimbatore',
    slug: 'coimbatore-institute-of-technology',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'GOVT_AIDED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-COI',
    districtName: 'Coimbatore',
    city: 'Coimbatore',
    address: 'Civil Aerodrome Post, Coimbatore - 641014',
    pincode: '641014',
    website: 'https://www.cit.edu.in',
    establishedYear: 1956,
    accreditation: 'NAAC A+ Grade',
    affiliatingUniversity: 'Anna University, Chennai',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['CIT', 'CIT Coimbatore', 'Coimbatore Institute of Technology', 'Aerodrome CIT'],
    studentCount: 4500,
    mentorCount: 3,
    eventCount: 15,
    ambassadorCount: 2,
    tags: ['Engineering', 'Autonomous', 'Govt Aided', 'Coimbatore'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-ssn-chennai',
    aisheCode: 'C-16621',
    name: 'SSN College of Engineering',
    shortName: 'SSN CE',
    slug: 'ssn-college-of-engineering',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-CHE2',
    districtName: 'Chengalpattu',
    city: 'Kalavakkam, Chennai',
    address: 'Old Mahabalipuram Road (OMR), Kalavakkam - 603110',
    pincode: '603110',
    website: 'https://www.ssn.edu.in',
    establishedYear: 1996,
    accreditation: 'NAAC A++ Grade / NBA',
    affiliatingUniversity: 'Anna University, Chennai',
    nirfRank: 45,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['SSN', 'SSN College', 'Sri Sivasubramaniya Nadar College', 'SSNCE', 'SSN OMR'],
    studentCount: 5200,
    mentorCount: 4,
    eventCount: 19,
    ambassadorCount: 3,
    tags: ['Engineering', 'Autonomous', 'OMR Chennai', 'Research'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-vit-vellore',
    aisheCode: 'U-0500',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    slug: 'vit-vellore',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PRIVATE_DEEMED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-VEL',
    districtName: 'Vellore',
    city: 'Vellore',
    address: 'Katpadi, Vellore - 632014',
    pincode: '632014',
    website: 'https://vit.ac.in',
    establishedYear: 1984,
    accreditation: 'NAAC A++ Grade / IoE Status',
    nirfRank: 11,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['VIT', 'VIT Vellore', 'Vellore Institute of Technology', 'VIT Riviera', 'VIT GraVITas'],
    studentCount: 32000,
    mentorCount: 10,
    eventCount: 60,
    ambassadorCount: 8,
    tags: ['Deemed University', 'Vellore', 'Engineering', 'Large Scale'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-srm-chennai',
    aisheCode: 'U-0473',
    name: 'SRM Institute of Science and Technology (Kattankulathur Campus)',
    shortName: 'SRM IST KTR',
    slug: 'srm-ist-kattankulathur',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PRIVATE_DEEMED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-CHE2',
    districtName: 'Chengalpattu',
    city: 'Kattankulathur, Chennai',
    address: 'SRM Nagar, Kattankulathur - 603203',
    pincode: '603203',
    website: 'https://www.srmist.edu.in',
    establishedYear: 1985,
    accreditation: 'NAAC A++ Grade',
    nirfRank: 18,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['SRM', 'SRM University', 'SRM KTR', 'SRM IST', 'Milan SRM'],
    studentCount: 40000,
    mentorCount: 8,
    eventCount: 48,
    ambassadorCount: 6,
    tags: ['Deemed University', 'SRM KTR', 'Engineering', 'Milan'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-tce-madurai',
    aisheCode: 'C-26792',
    name: 'Thiagarajar College of Engineering',
    shortName: 'TCE Madurai',
    slug: 'thiagarajar-college-of-engineering',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'GOVT_AIDED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-MAD',
    districtName: 'Madurai',
    city: 'Madurai',
    address: 'Tirupparankundram, Madurai - 625015',
    pincode: '625015',
    website: 'https://www.tce.edu',
    establishedYear: 1957,
    accreditation: 'NAAC A+ Grade',
    affiliatingUniversity: 'Anna University, Chennai',
    nirfRank: 85,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['TCE', 'TCE Madurai', 'Thiagarajar College of Engineering', 'Tirupparankundram TCE'],
    studentCount: 4800,
    mentorCount: 3,
    eventCount: 14,
    ambassadorCount: 2,
    tags: ['Engineering', 'Autonomous', 'Govt Aided', 'Madurai'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-gct-coimbatore',
    aisheCode: 'C-41047',
    name: 'Government College of Technology, Coimbatore',
    shortName: 'GCT Coimbatore',
    slug: 'gct-coimbatore',
    institutionType: 'COLLEGE',
    institutionCategory: 'GOVERNMENT_COLLEGE',
    managementType: 'STATE_GOVT',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-COI',
    districtName: 'Coimbatore',
    city: 'Coimbatore',
    address: 'Thadagam Road, Coimbatore - 641013',
    pincode: '641013',
    website: 'https://gct.ac.in',
    establishedYear: 1945,
    accreditation: 'NBA / NAAC A',
    affiliatingUniversity: 'Anna University, Chennai',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['GCT', 'GCT Coimbatore', 'Govt College of Technology Coimbatore'],
    studentCount: 3500,
    mentorCount: 3,
    eventCount: 12,
    ambassadorCount: 2,
    tags: ['Government', 'Autonomous', 'Coimbatore'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-loyola-chennai',
    aisheCode: 'C-43826',
    name: 'Loyola College, Chennai',
    shortName: 'Loyola College',
    slug: 'loyola-college-chennai',
    institutionType: 'COLLEGE',
    institutionCategory: 'ARTS_SCIENCE_COLLEGE',
    managementType: 'GOVT_AIDED',
    stateId: 'TN',
    stateName: 'Tamil Nadu',
    districtId: 'TN-CHE',
    districtName: 'Chennai',
    city: 'Chennai',
    address: 'Sterling Road, Nungambakkam, Chennai - 600034',
    pincode: '600034',
    website: 'https://www.loyolacollege.edu',
    establishedYear: 1925,
    accreditation: 'NAAC A++ Grade',
    affiliatingUniversity: 'University of Madras',
    nirfRank: 7,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['Loyola', 'Loyola Chennai', 'Loyola College Chennai', 'Nungambakkam Loyola'],
    studentCount: 9500,
    mentorCount: 4,
    eventCount: 22,
    ambassadorCount: 3,
    tags: ['Arts and Science', 'Autonomous', 'Govt Aided', 'Top College', 'Chennai'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Karnataka
  {
    id: 'inst-iisc-bangalore',
    aisheCode: 'U-0220',
    name: 'Indian Institute of Science Bangalore',
    shortName: 'IISc Bangalore',
    slug: 'iisc-bangalore',
    institutionType: 'INSTITUTE',
    institutionCategory: 'CENTRAL_UNIVERSITY',
    managementType: 'CENTRAL_GOVT',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'CV Raman Road, Bengaluru - 560012',
    pincode: '560012',
    website: 'https://iisc.ac.in',
    establishedYear: 1909,
    accreditation: 'Institute of Eminence (IoE) / NIRF Univ #1',
    nirfRank: 2,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IISc', 'IISc Bangalore', 'Indian Institute of Science', 'Pravega IISc'],
    studentCount: 4200,
    mentorCount: 7,
    eventCount: 30,
    ambassadorCount: 4,
    tags: ['Research', 'IISc', 'Premier', 'Bengaluru'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-rvce-bangalore',
    aisheCode: 'C-1259',
    name: 'R.V. College of Engineering',
    shortName: 'RVCE Bangalore',
    slug: 'rv-college-of-engineering',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Mysore Road, RV Vidyanikethan Post, Bengaluru - 560059',
    pincode: '560059',
    website: 'https://rvce.edu.in',
    establishedYear: 1963,
    accreditation: 'NAAC A+ Grade / NBA',
    affiliatingUniversity: 'Visvesvaraya Technological University (VTU)',
    nirfRank: 89,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['RVCE', 'RV College', 'Rashtreeya Vidyalaya College of Engineering', '8th Mile Mysore Road'],
    studentCount: 5400,
    mentorCount: 5,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['Autonomous', 'VTU', 'Bengaluru', 'Engineering Top'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-bmsce-bangalore',
    aisheCode: 'C-1260',
    name: 'BMS College of Engineering',
    shortName: 'BMSCE',
    slug: 'bms-college-of-engineering',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'GOVT_AIDED',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'Bull Temple Road, Basavanagudi, Bengaluru - 560019',
    pincode: '560019',
    website: 'https://bmsce.ac.in',
    establishedYear: 1946,
    accreditation: 'NAAC A++ Grade / NBA',
    affiliatingUniversity: 'Visvesvaraya Technological University (VTU)',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['BMSCE', 'BMS College', 'Basavanagudi BMS', 'BMS Engineering', 'Utsav BMSCE'],
    studentCount: 5800,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['Autonomous', 'Govt Aided', 'Bengaluru', 'Heritage'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-pes-university',
    aisheCode: 'U-0744',
    name: 'PES University (Ring Road Campus)',
    shortName: 'PES University',
    slug: 'pes-university',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'PRIVATE_UNIVERSITY',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: '100 Feet Ring Road, BSK III Stage, Bengaluru - 560085',
    pincode: '560085',
    website: 'https://pes.edu',
    establishedYear: 1972,
    accreditation: 'NAAC A+ Grade',
    nirfRank: 101,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['PES', 'PESIT', 'PES University', 'PES Ring Road', 'PES Banashankari'],
    studentCount: 12000,
    mentorCount: 5,
    eventCount: 25,
    ambassadorCount: 4,
    tags: ['Private University', 'Bengaluru', 'Engineering', 'Tech'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-nitk-surathkal',
    aisheCode: 'U-0237',
    name: 'National Institute of Technology Karnataka, Surathkal',
    shortName: 'NITK Surathkal',
    slug: 'nitk-surathkal',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-DKA',
    districtName: 'Dakshina Kannada (Mangaluru)',
    city: 'Mangaluru',
    address: 'NH 66, Srinivasnagar, Surathkal, Mangaluru - 575025',
    pincode: '575025',
    website: 'https://www.nitk.ac.in',
    establishedYear: 1960,
    accreditation: 'Institute of National Importance',
    nirfRank: 12,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NITK', 'NITK Surathkal', 'KREC Surathkal', 'NIT Karnataka', 'Engineer NITK', 'Incident NITK'],
    studentCount: 6500,
    mentorCount: 6,
    eventCount: 26,
    ambassadorCount: 4,
    tags: ['NIT', 'Central Govt', 'Mangaluru', 'Surathkal Beach'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iiit-bangalore',
    aisheCode: 'U-0222',
    name: 'International Institute of Information Technology Bangalore',
    shortName: 'IIIT Bangalore',
    slug: 'iiit-bangalore',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIIT',
    managementType: 'PUBLIC_PRIVATE_PARTNERSHIP',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: '26/C, Electronic City Phase 1, Hosur Road, Bengaluru - 560100',
    pincode: '560100',
    website: 'https://www.iiitb.ac.in',
    establishedYear: 1999,
    accreditation: 'NAAC A+ Grade',
    nirfRank: 74,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIIT-B', 'IIIT Bangalore', 'IIITB', 'Electronic City IIIT'],
    studentCount: 1500,
    mentorCount: 4,
    eventCount: 16,
    ambassadorCount: 2,
    tags: ['IIIT', 'Electronic City', 'Computer Science', 'Bengaluru'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-msrit-bangalore',
    aisheCode: 'C-1263',
    name: 'Ramaiah Institute of Technology',
    shortName: 'MSRIT Bangalore',
    slug: 'ramaiah-institute-of-technology',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-BLRU',
    districtName: 'Bengaluru Urban',
    city: 'Bengaluru',
    address: 'MSR Nagar, MSRIT Post, Bengaluru - 560054',
    pincode: '560054',
    website: 'https://www.msrit.edu',
    establishedYear: 1962,
    accreditation: 'NAAC A+ Grade / NBA',
    affiliatingUniversity: 'Visvesvaraya Technological University (VTU)',
    nirfRank: 78,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['MSRIT', 'Ramaiah', 'MS Ramaiah Institute of Technology', 'MSRIT Mathikere', 'Udbhav MSRIT'],
    studentCount: 6200,
    mentorCount: 4,
    eventCount: 19,
    ambassadorCount: 3,
    tags: ['Autonomous', 'VTU', 'Mathikere', 'Bengaluru'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-manipal-mit',
    aisheCode: 'C-1681',
    name: 'Manipal Institute of Technology (MAHE)',
    shortName: 'MIT Manipal',
    slug: 'manipal-institute-of-technology',
    institutionType: 'COLLEGE',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PRIVATE_DEEMED',
    stateId: 'KA',
    stateName: 'Karnataka',
    districtId: 'KA-UDU',
    districtName: 'Udupi',
    city: 'Manipal, Udupi',
    address: 'Udupi - Karkala Rd, Eshwar Nagar, Manipal - 576104',
    pincode: '576104',
    website: 'https://manipal.edu/mit',
    establishedYear: 1957,
    accreditation: 'NAAC A++ Grade / IoE Status',
    nirfRank: 61,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['MIT Manipal', 'Manipal University', 'MAHE Manipal', 'Revels Manipal', 'TechTatva'],
    studentCount: 9500,
    mentorCount: 5,
    eventCount: 32,
    ambassadorCount: 4,
    tags: ['MAHE', 'Manipal', 'Private Deemed', 'Engineering'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Maharashtra
  {
    id: 'inst-iit-bombay',
    aisheCode: 'U-0306',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    slug: 'iit-bombay',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-MSU',
    districtName: 'Mumbai Suburban',
    city: 'Mumbai',
    address: 'Main Gate Rd, IIT Area, Powai, Mumbai - 400076',
    pincode: '400076',
    website: 'https://www.iitb.ac.in',
    establishedYear: 1958,
    accreditation: 'Institute of Eminence (IoE)',
    nirfRank: 3,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Bombay', 'IITB', 'IIT Powai', 'Mood Indigo', 'Techfest IIT Bombay'],
    studentCount: 12500,
    mentorCount: 8,
    eventCount: 45,
    ambassadorCount: 5,
    tags: ['IIT', 'Central Govt', 'Powai Mumbai', 'Mood Indigo', 'Techfest'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-coep-pune',
    aisheCode: 'U-1193',
    name: 'COEP Technological University (College of Engineering Pune)',
    shortName: 'COEP Pune',
    slug: 'coep-technological-university',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-PUN',
    districtName: 'Pune',
    city: 'Pune',
    address: 'Wellesley Road, Shivajinagar, Pune - 411005',
    pincode: '411005',
    website: 'https://www.coep.org.in',
    establishedYear: 1854,
    accreditation: 'NBA / NAAC A+',
    nirfRank: 73,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['COEP', 'COEP Pune', 'College of Engineering Pune', 'Shivajinagar COEP', 'MindSpark COEP', 'Zest COEP'],
    studentCount: 4800,
    mentorCount: 5,
    eventCount: 22,
    ambassadorCount: 3,
    tags: ['State University', 'Pune', 'Historic 1854', 'Top Engineering'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-vjti-mumbai',
    aisheCode: 'C-33827',
    name: 'Veermata Jijabai Technological Institute (VJTI)',
    shortName: 'VJTI Mumbai',
    slug: 'vjti-mumbai',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'STATE_GOVT',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-MUM',
    districtName: 'Mumbai City',
    city: 'Mumbai',
    address: 'H. R. Mahajani Marg, Matunga, Mumbai - 400019',
    pincode: '400019',
    website: 'https://vjti.ac.in',
    establishedYear: 1887,
    accreditation: 'NAAC A / NBA',
    affiliatingUniversity: 'University of Mumbai',
    nirfRank: 101,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['VJTI', 'VJTI Mumbai', 'Victoria Jubilee Technical Institute', 'Matunga VJTI', 'Technovanza VJTI'],
    studentCount: 4200,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['Autonomous', 'State Govt', 'Matunga', 'Mumbai'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-vnit-nagpur',
    aisheCode: 'U-0334',
    name: 'Visvesvaraya National Institute of Technology, Nagpur',
    shortName: 'VNIT Nagpur',
    slug: 'vnit-nagpur',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-NAG',
    districtName: 'Nagpur',
    city: 'Nagpur',
    address: 'South Ambazari Road, Ambazari, Nagpur - 440010',
    pincode: '440010',
    website: 'https://vnit.ac.in',
    establishedYear: 1960,
    accreditation: 'Institute of National Importance',
    nirfRank: 41,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['VNIT', 'VNIT Nagpur', 'VRCE Nagpur', 'Aarohi VNIT', 'Axis VNIT'],
    studentCount: 5200,
    mentorCount: 4,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Nagpur'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-pict-pune',
    aisheCode: 'C-41724',
    name: 'Pune Institute of Computer Technology (PICT)',
    shortName: 'PICT Pune',
    slug: 'pict-pune',
    institutionType: 'COLLEGE',
    institutionCategory: 'AFFILIATED_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-PUN',
    districtName: 'Pune',
    city: 'Pune',
    address: 'Survey No. 27, Near Trimurti Chowk, Dhankawadi, Pune - 411043',
    pincode: '411043',
    website: 'https://pict.edu',
    establishedYear: 1983,
    accreditation: 'NAAC A+ Grade / NBA',
    affiliatingUniversity: 'Savitribai Phule Pune University (SPPU)',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['PICT', 'PICT Pune', 'Pune Institute of Computer Technology', 'Dhankawadi PICT', 'Impetus PICT', 'Concepts PICT'],
    studentCount: 3600,
    mentorCount: 4,
    eventCount: 16,
    ambassadorCount: 2,
    tags: ['SPPU', 'Pune', 'Computer Engineering Hub', 'Coding Culture'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-spit-mumbai',
    aisheCode: 'C-33758',
    name: 'Sardar Patel Institute of Technology (SPIT)',
    shortName: 'SPIT Mumbai',
    slug: 'spit-mumbai',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'MH',
    stateName: 'Maharashtra',
    districtId: 'MH-MSU',
    districtName: 'Mumbai Suburban',
    city: 'Mumbai',
    address: 'Bhavans Campus, Munshi Nagar, Andheri West, Mumbai - 400058',
    pincode: '400058',
    website: 'https://www.spit.ac.in',
    establishedYear: 2005,
    accreditation: 'NAAC A+ Grade / NBA',
    affiliatingUniversity: 'University of Mumbai',
    nirfRank: 125,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['SPIT', 'SPIT Mumbai', 'Sardar Patel Institute of Technology', 'Andheri SPIT', 'Oculus SPIT'],
    studentCount: 2400,
    mentorCount: 3,
    eventCount: 14,
    ambassadorCount: 2,
    tags: ['Autonomous', 'Andheri West', 'Mumbai', 'Tech'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Delhi NCR
  {
    id: 'inst-iit-delhi',
    aisheCode: 'U-0092',
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    slug: 'iit-delhi',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'DL',
    stateName: 'Delhi (NCT)',
    districtId: 'DL-SDL',
    districtName: 'South Delhi',
    city: 'New Delhi',
    address: 'Hauz Khas, New Delhi - 110016',
    pincode: '110016',
    website: 'https://home.iitd.ac.in',
    establishedYear: 1961,
    accreditation: 'Institute of Eminence (IoE)',
    nirfRank: 2,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Delhi', 'IITD', 'Hauz Khas IIT', 'Rendezvous IIT Delhi', 'Tryst IIT Delhi'],
    studentCount: 11800,
    mentorCount: 8,
    eventCount: 40,
    ambassadorCount: 5,
    tags: ['IIT', 'Central Govt', 'Hauz Khas', 'Delhi'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-dtu-delhi',
    aisheCode: 'U-0100',
    name: 'Delhi Technological University (formerly DCE)',
    shortName: 'DTU Delhi',
    slug: 'delhi-technological-university',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'DL',
    stateName: 'Delhi (NCT)',
    districtId: 'DL-ND2',
    districtName: 'North Delhi',
    city: 'Delhi',
    address: 'Shahbad Daulatpur, Main Bawana Road, Delhi - 110042',
    pincode: '110042',
    website: 'http://dtu.ac.in',
    establishedYear: 1941,
    accreditation: 'NAAC A Grade',
    nirfRank: 29,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['DTU', 'DCE', 'Delhi Technological University', 'Delhi College of Engineering', 'Engifest DTU', 'Invictus DTU'],
    studentCount: 13000,
    mentorCount: 6,
    eventCount: 30,
    ambassadorCount: 4,
    tags: ['State University', 'Bawana', 'Delhi', 'Engifest', 'Historic DCE'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-nsut-delhi',
    aisheCode: 'U-0975',
    name: 'Netaji Subhas University of Technology (formerly NSIT)',
    shortName: 'NSUT Delhi',
    slug: 'nsut-delhi',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'DL',
    stateName: 'Delhi (NCT)',
    districtId: 'DL-SWD',
    districtName: 'South West Delhi',
    city: 'Dwarka, New Delhi',
    address: 'Sector 3, Dwarka, New Delhi - 110078',
    pincode: '110078',
    website: 'http://www.nsut.ac.in',
    establishedYear: 1983,
    accreditation: 'NAAC A Grade',
    nirfRank: 60,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NSUT', 'NSIT', 'Netaji Subhas Institute of Technology', 'Dwarka NSUT', 'Moksha NSUT', 'Inception NSUT'],
    studentCount: 8500,
    mentorCount: 5,
    eventCount: 24,
    ambassadorCount: 3,
    tags: ['State University', 'Dwarka', 'Delhi', 'Engineering'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iiit-delhi',
    aisheCode: 'U-0105',
    name: 'Indraprastha Institute of Information Technology Delhi',
    shortName: 'IIIT Delhi',
    slug: 'iiit-delhi',
    institutionType: 'INSTITUTE',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'DL',
    stateName: 'Delhi (NCT)',
    districtId: 'DL-SDL',
    districtName: 'South Delhi',
    city: 'Okhla, New Delhi',
    address: 'Okhla Industrial Estate Phase III, Near Govind Puri Metro, New Delhi - 110020',
    pincode: '110020',
    website: 'https://www.iiitd.ac.in',
    establishedYear: 2008,
    accreditation: 'NAAC A Grade / NBA',
    nirfRank: 75,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIIT-D', 'IIIT Delhi', 'IIITD', 'Indraprastha IT Delhi', 'Esya IIITD', 'Odyssey IIITD'],
    studentCount: 3200,
    mentorCount: 4,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['State University', 'Okhla', 'Computer Science', 'AI Hub'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Telangana
  {
    id: 'inst-iiit-hyderabad',
    aisheCode: 'U-0013',
    name: 'International Institute of Information Technology Hyderabad',
    shortName: 'IIIT Hyderabad',
    slug: 'iiit-hyderabad',
    institutionType: 'INSTITUTE',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PUBLIC_PRIVATE_PARTNERSHIP',
    stateId: 'TG',
    stateName: 'Telangana',
    districtId: 'TG-HYD',
    districtName: 'Hyderabad',
    city: 'Gachibowli, Hyderabad',
    address: 'Prof. C R Rao Road, Gachibowli, Hyderabad - 500032',
    pincode: '500032',
    website: 'https://www.iiit.ac.in',
    establishedYear: 1998,
    accreditation: 'NAAC A++ Grade',
    nirfRank: 55,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIIT-H', 'IIIT Hyderabad', 'IIITH', 'Gachibowli IIIT', 'Felicity IIITH'],
    studentCount: 2200,
    mentorCount: 6,
    eventCount: 25,
    ambassadorCount: 3,
    tags: ['PPP', 'Gachibowli', 'Top Coding & Research', 'Hyderabad'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iit-hyderabad',
    aisheCode: 'U-0015',
    name: 'Indian Institute of Technology Hyderabad',
    shortName: 'IIT Hyderabad',
    slug: 'iit-hyderabad',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'TG',
    stateName: 'Telangana',
    districtId: 'TG-SAN',
    districtName: 'Sangareddy',
    city: 'Kandi, Sangareddy',
    address: 'Near NH-65, Sangareddy, Kandi - 502285',
    pincode: '502285',
    website: 'https://www.iith.ac.in',
    establishedYear: 2008,
    accreditation: 'Institute of National Importance',
    nirfRank: 8,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Hyderabad', 'IITH', 'Elan & Envision', 'Kandi IITH'],
    studentCount: 4800,
    mentorCount: 5,
    eventCount: 22,
    ambassadorCount: 3,
    tags: ['IIT', 'Central Govt', 'Top 10 Engineering', 'Sangareddy'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-nit-warangal',
    aisheCode: 'U-0025',
    name: 'National Institute of Technology Warangal',
    shortName: 'NIT Warangal',
    slug: 'nit-warangal',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'TG',
    stateName: 'Telangana',
    districtId: 'TG-HAN',
    districtName: 'Hanamkonda (Warangal)',
    city: 'Warangal',
    address: 'National Highway 563, Kazipet, Hanamkonda, Warangal - 506004',
    pincode: '506004',
    website: 'https://www.nitw.ac.in',
    establishedYear: 1959,
    accreditation: 'Institute of National Importance',
    nirfRank: 21,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NIT Warangal', 'NITW', 'REC Warangal', 'Technozion NITW', 'SpringSpree NITW'],
    studentCount: 6200,
    mentorCount: 5,
    eventCount: 24,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Kazipet', 'Warangal'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-cbit-hyderabad',
    aisheCode: 'C-25622',
    name: 'Chaitanya Bharathi Institute of Technology (CBIT)',
    shortName: 'CBIT Hyderabad',
    slug: 'cbit-hyderabad',
    institutionType: 'COLLEGE',
    institutionCategory: 'AUTONOMOUS_COLLEGE',
    managementType: 'PRIVATE_UNAIDED',
    stateId: 'TG',
    stateName: 'Telangana',
    districtId: 'TG-RAN',
    districtName: 'Rangareddy',
    city: 'Gandipet, Hyderabad',
    address: 'Post Office Kokapet, Gandipet, Hyderabad - 500075',
    pincode: '500075',
    website: 'https://www.cbit.ac.in',
    establishedYear: 1979,
    accreditation: 'NAAC A++ Grade / NBA',
    affiliatingUniversity: 'Osmania University, Hyderabad',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['CBIT', 'CBIT Hyderabad', 'Chaitanya Bharathi', 'Gandipet CBIT', 'Sudhee CBIT', 'Shruthi CBIT'],
    studentCount: 6500,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['Autonomous', 'Osmania', 'Gandipet', 'Hyderabad'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-jntuh-hyderabad',
    aisheCode: 'U-0017',
    name: 'Jawaharlal Nehru Technological University Hyderabad (JNTUH CEH)',
    shortName: 'JNTU Hyderabad',
    slug: 'jntu-hyderabad',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'TG',
    stateName: 'Telangana',
    districtId: 'TG-HYD',
    districtName: 'Hyderabad',
    city: 'Kukatpally, Hyderabad',
    address: 'Kukatpally Housing Board Colony, Kukatpally, Hyderabad - 500085',
    pincode: '500085',
    website: 'https://jntuh.ac.in',
    establishedYear: 1965,
    accreditation: 'NAAC A+ Grade',
    nirfRank: 83,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['JNTU', 'JNTUH', 'JNTU Hyderabad', 'Kukatpally JNTU', 'JNTUCEH'],
    studentCount: 9000,
    mentorCount: 4,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['State University', 'Kukatpally', 'Engineering', 'Hyderabad'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Andhra Pradesh
  {
    id: 'inst-iit-tirupati',
    aisheCode: 'U-0842',
    name: 'Indian Institute of Technology Tirupati',
    shortName: 'IIT Tirupati',
    slug: 'iit-tirupati',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'AP',
    stateName: 'Andhra Pradesh',
    districtId: 'AP-TPT',
    districtName: 'Tirupati',
    city: 'Yerpedu, Tirupati',
    address: 'Yerpedu - Venkatagiri Road, Yerpedu Post, Tirupati - 517619',
    pincode: '517619',
    website: 'https://iittp.ac.in',
    establishedYear: 2015,
    accreditation: 'Institute of National Importance',
    nirfRank: 59,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Tirupati', 'IITTP', 'Yerpedu IIT', 'Tirupati IIT', 'Tirutsava'],
    studentCount: 2000,
    mentorCount: 4,
    eventCount: 14,
    ambassadorCount: 2,
    tags: ['IIT', 'Central Govt', 'Yerpedu', 'Tirupati'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-andhra-univ',
    aisheCode: 'U-0002',
    name: 'Andhra University College of Engineering, Visakhapatnam',
    shortName: 'AU Vizag',
    slug: 'andhra-university-college-of-engineering',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'AP',
    stateName: 'Andhra Pradesh',
    districtId: 'AP-VSP',
    districtName: 'Visakhapatnam',
    city: 'Visakhapatnam',
    address: 'Waltair Junction, Visakhapatnam - 530003',
    pincode: '530003',
    website: 'https://andhrauniversity.edu.in',
    establishedYear: 1926,
    accreditation: 'NAAC A++ Grade',
    nirfRank: 43,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['Andhra University', 'AUCE', 'AU Vizag', 'Waltair AU', 'AU Engineering'],
    studentCount: 11000,
    mentorCount: 5,
    eventCount: 22,
    ambassadorCount: 3,
    tags: ['State University', 'Waltair', 'Vizag', 'Historic 1926'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Kerala
  {
    id: 'inst-nit-calicut',
    aisheCode: 'U-0263',
    name: 'National Institute of Technology Calicut',
    shortName: 'NIT Calicut',
    slug: 'nit-calicut',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'KL',
    stateName: 'Kerala',
    districtId: 'KL-KOZ',
    districtName: 'Kozhikode',
    city: 'Chathamangalam, Kozhikode',
    address: 'NIT Campus P.O., Calicut, Kerala - 673601',
    pincode: '673601',
    website: 'https://nitc.ac.in',
    establishedYear: 1961,
    accreditation: 'Institute of National Importance',
    nirfRank: 23,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NIT Calicut', 'NITC', 'CREC Calicut', 'Tathva NITC', 'Ragam NITC'],
    studentCount: 6400,
    mentorCount: 5,
    eventCount: 25,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Chathamangalam', 'Kozhikode'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-cet-trivandrum',
    aisheCode: 'C-43890',
    name: 'College of Engineering Trivandrum (CET)',
    shortName: 'CET Trivandrum',
    slug: 'college-of-engineering-trivandrum',
    institutionType: 'COLLEGE',
    institutionCategory: 'GOVERNMENT_COLLEGE',
    managementType: 'STATE_GOVT',
    stateId: 'KL',
    stateName: 'Kerala',
    districtId: 'KL-TVM',
    districtName: 'Thiruvananthapuram',
    city: 'Thiruvananthapuram',
    address: 'Engineering College P.O., Sreekaryam, Thiruvananthapuram - 695016',
    pincode: '695016',
    website: 'https://www.cet.ac.in',
    establishedYear: 1939,
    accreditation: 'NBA / NAAC A',
    affiliatingUniversity: 'APJ Abdul Kalam Technological University (KTU)',
    nirfRank: 85,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['CET', 'CET Trivandrum', 'College of Engineering Trivandrum', 'Dhwani CET', 'Drishti CET'],
    studentCount: 4500,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['Government', 'KTU', 'Sreekaryam', 'Trivandrum'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // West Bengal
  {
    id: 'inst-iit-kharagpur',
    aisheCode: 'U-0570',
    name: 'Indian Institute of Technology Kharagpur',
    shortName: 'IIT Kharagpur',
    slug: 'iit-kharagpur',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'WB',
    stateName: 'West Bengal',
    districtId: 'WB-PAS',
    districtName: 'Paschim Bardhaman (Durgapur/Asansol)',
    city: 'Kharagpur',
    address: 'Kharagpur, West Bengal - 721302',
    pincode: '721302',
    website: 'http://www.iitkgp.ac.in',
    establishedYear: 1951,
    accreditation: 'Institute of Eminence (IoE) / First IIT',
    nirfRank: 6,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Kharagpur', 'IIT KGP', 'IITKGP', 'Spring Fest IIT KGP', 'Kshitij IIT KGP'],
    studentCount: 15000,
    mentorCount: 8,
    eventCount: 44,
    ambassadorCount: 5,
    tags: ['IIT', 'Central Govt', 'First IIT', 'Kharagpur', 'Spring Fest'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-jadavpur-univ',
    aisheCode: 'U-0573',
    name: 'Jadavpur University, Kolkata',
    shortName: 'Jadavpur University',
    slug: 'jadavpur-university',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'STATE_UNIVERSITY',
    managementType: 'STATE_GOVT',
    stateId: 'WB',
    stateName: 'West Bengal',
    districtId: 'WB-KOL',
    districtName: 'Kolkata',
    city: 'Kolkata',
    address: '188, Raja S.C. Mallick Rd, Jadavpur, Kolkata - 700032',
    pincode: '700032',
    website: 'http://www.jaduniv.edu.in',
    establishedYear: 1955,
    accreditation: 'NAAC A Grade',
    nirfRank: 10,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['JU', 'JU Kolkata', 'Jadavpur University', 'Sanskriti JU', 'Srijan JU'],
    studentCount: 11500,
    mentorCount: 6,
    eventCount: 28,
    ambassadorCount: 4,
    tags: ['State University', 'Kolkata', 'Top Research', 'Affordable Excellence'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Uttar Pradesh
  {
    id: 'inst-iit-kanpur',
    aisheCode: 'U-0504',
    name: 'Indian Institute of Technology Kanpur',
    shortName: 'IIT Kanpur',
    slug: 'iit-kanpur',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'UP',
    stateName: 'Uttar Pradesh',
    districtId: 'UP-KAN',
    districtName: 'Kanpur Nagar',
    city: 'Kalyanpur, Kanpur',
    address: 'Kalyanpur, Kanpur - 208016',
    pincode: '208016',
    website: 'https://www.iitk.ac.in',
    establishedYear: 1959,
    accreditation: 'Institute of National Importance',
    nirfRank: 4,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Kanpur', 'IITK', 'Antaragni IITK', 'Techkriti IITK', 'Udghosh IITK'],
    studentCount: 8800,
    mentorCount: 7,
    eventCount: 38,
    ambassadorCount: 4,
    tags: ['IIT', 'Central Govt', 'Kanpur', 'Computer Science Leader'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iit-bhu-varanasi',
    aisheCode: 'U-0500B',
    name: 'Indian Institute of Technology (BHU) Varanasi',
    shortName: 'IIT (BHU) Varanasi',
    slug: 'iit-bhu-varanasi',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'UP',
    stateName: 'Uttar Pradesh',
    districtId: 'UP-VAR',
    districtName: 'Varanasi',
    city: 'Varanasi',
    address: 'Banaras Hindu University Campus, Varanasi - 221005',
    pincode: '221005',
    website: 'https://www.iitbhu.ac.in',
    establishedYear: 1919,
    accreditation: 'Institute of National Importance',
    nirfRank: 15,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT BHU', 'IT BHU', 'IIT Varanasi', 'Technex IIT BHU', 'Kashiyatra IIT BHU'],
    studentCount: 7200,
    mentorCount: 6,
    eventCount: 26,
    ambassadorCount: 3,
    tags: ['IIT', 'Central Govt', 'BHU Varanasi', 'Historic 1919'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-mnnit-allahabad',
    aisheCode: 'U-0529',
    name: 'Motilal Nehru National Institute of Technology Allahabad, Prayagraj',
    shortName: 'MNNIT Allahabad',
    slug: 'mnnit-allahabad',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'UP',
    stateName: 'Uttar Pradesh',
    districtId: 'UP-PRAY',
    districtName: 'Prayagraj (Allahabad)',
    city: 'Prayagraj',
    address: 'Barrister Mullah Colony, MNNIT Allahabad Campus, Teliarganj, Prayagraj - 211004',
    pincode: '211004',
    website: 'http://www.mnnit.ac.in',
    establishedYear: 1961,
    accreditation: 'Institute of National Importance',
    nirfRank: 49,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['MNNIT', 'MNNIT Allahabad', 'MNREC Allahabad', 'MNNIT Prayagraj', 'Avishkar MNNIT', 'Culrav MNNIT'],
    studentCount: 5600,
    mentorCount: 5,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Prayagraj', 'Teliarganj'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Rajasthan
  {
    id: 'inst-bits-pilani',
    aisheCode: 'U-0391',
    name: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    slug: 'bits-pilani',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PRIVATE_DEEMED',
    stateId: 'RJ',
    stateName: 'Rajasthan',
    districtId: 'RJ-JAI',
    districtName: 'Jaipur',
    city: 'Pilani, Jhunjhunu',
    address: 'Vidya Vihar Campus, Pilani - 333031',
    pincode: '333031',
    website: 'https://www.bits-pilani.ac.in',
    establishedYear: 1964,
    accreditation: 'Institute of Eminence (IoE)',
    nirfRank: 20,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['BITS Pilani', 'BITS', 'Birla Institute Pilani', 'Oasis BITS', 'APOGEE BITS', 'BOSM BITS'],
    studentCount: 5000,
    mentorCount: 6,
    eventCount: 30,
    ambassadorCount: 4,
    tags: ['IoE', 'Pilani', 'Top Private Institution', 'Oasis', 'APOGEE'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-mnit-jaipur',
    aisheCode: 'U-0399',
    name: 'Malaviya National Institute of Technology Jaipur',
    shortName: 'MNIT Jaipur',
    slug: 'mnit-jaipur',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'RJ',
    stateName: 'Rajasthan',
    districtId: 'RJ-JAI',
    districtName: 'Jaipur',
    city: 'Jaipur',
    address: 'Jawahar Lal Nehru Marg, Jhalana Doongri, Jaipur - 302017',
    pincode: '302017',
    website: 'https://www.mnit.ac.in',
    establishedYear: 1963,
    accreditation: 'Institute of National Importance',
    nirfRank: 37,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['MNIT Jaipur', 'MNIT', 'MREC Jaipur', 'Blitzschlag MNIT', 'Sphurti MNIT'],
    studentCount: 5500,
    mentorCount: 5,
    eventCount: 20,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Jaipur', 'Pink City'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Punjab / Chandigarh
  {
    id: 'inst-thapar-patiala',
    aisheCode: 'U-0387',
    name: 'Thapar Institute of Engineering and Technology (TIET), Patiala',
    shortName: 'Thapar Patiala',
    slug: 'thapar-institute-of-engineering-and-technology',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'PRIVATE_DEEMED',
    stateId: 'PB',
    stateName: 'Punjab',
    districtId: 'PB-PAT',
    districtName: 'Patiala',
    city: 'Patiala',
    address: 'Bhadson Rd, Adarsh Nagar, Prem Nagar, Patiala - 147004',
    pincode: '147004',
    website: 'http://www.thapar.edu',
    establishedYear: 1956,
    accreditation: 'NAAC A+ Grade',
    nirfRank: 22,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['Thapar', 'TIET', 'Thapar University', 'Thapar Patiala', 'Saturnalia Thapar'],
    studentCount: 11000,
    mentorCount: 5,
    eventCount: 26,
    ambassadorCount: 4,
    tags: ['Deemed University', 'Patiala', 'Punjab', 'Engineering Top'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-pec-chandigarh',
    aisheCode: 'U-0097',
    name: 'Punjab Engineering College (Deemed to be University), Chandigarh',
    shortName: 'PEC Chandigarh',
    slug: 'punjab-engineering-college',
    institutionType: 'UNIVERSITY',
    institutionCategory: 'DEEMED_UNIVERSITY',
    managementType: 'CENTRAL_GOVT',
    stateId: 'CH',
    stateName: 'Chandigarh',
    districtId: 'CH-CHD',
    districtName: 'Chandigarh',
    city: 'Sector 12, Chandigarh',
    address: 'Sector 12, Chandigarh - 160012',
    pincode: '160012',
    website: 'https://pec.ac.in',
    establishedYear: 1921,
    accreditation: 'NAAC A Grade',
    nirfRank: 101,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['PEC', 'PEC Chandigarh', 'Punjab Engineering College', 'PECFEST', 'Sector 12 PEC'],
    studentCount: 3800,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['Deemed University', 'Chandigarh', 'Centenary 1921', 'PECFEST'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Uttarakhand
  {
    id: 'inst-iit-roorkee',
    aisheCode: 'U-0560',
    name: 'Indian Institute of Technology Roorkee (formerly Thomason College)',
    shortName: 'IIT Roorkee',
    slug: 'iit-roorkee',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'UK',
    stateName: 'Uttarakhand',
    districtId: 'UK-HAR',
    districtName: 'Haridwar (Roorkee)',
    city: 'Roorkee',
    address: 'Roorkee, Haridwar Highway, Roorkee - 247667',
    pincode: '247667',
    website: 'https://www.iitr.ac.in',
    establishedYear: 1847,
    accreditation: 'Institute of National Importance / Oldest Technical College in Asia',
    nirfRank: 5,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Roorkee', 'IITR', 'Thomason College', 'Cognizance IITR', 'Thomso IITR'],
    studentCount: 9200,
    mentorCount: 7,
    eventCount: 36,
    ambassadorCount: 4,
    tags: ['IIT', 'Central Govt', 'Oldest Tech College (1847)', 'Roorkee', 'Cognizance'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Odisha
  {
    id: 'inst-nit-rourkela',
    aisheCode: 'U-0355',
    name: 'National Institute of Technology Rourkela',
    shortName: 'NIT Rourkela',
    slug: 'nit-rourkela',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'OD',
    stateName: 'Odisha',
    districtId: 'OD-SUN',
    districtName: 'Sundargarh (Rourkela)',
    city: 'Rourkela',
    address: 'Sector 1, Rourkela, Sundargarh - 769008',
    pincode: '769008',
    website: 'https://www.nitrkl.ac.in',
    establishedYear: 1961,
    accreditation: 'Institute of National Importance',
    nirfRank: 16,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['NIT Rourkela', 'NITRKL', 'REC Rourkela', 'Innovision NITR', 'Nitinovision'],
    studentCount: 7200,
    mentorCount: 6,
    eventCount: 26,
    ambassadorCount: 4,
    tags: ['NIT', 'Central Govt', 'Rourkela', 'Top 20 Engineering'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-iiit-bhubaneswar',
    aisheCode: 'U-0743',
    name: 'International Institute of Information Technology Bhubaneswar',
    shortName: 'IIIT Bhubaneswar',
    slug: 'iiit-bhubaneswar',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIIT',
    managementType: 'STATE_GOVT',
    stateId: 'OD',
    stateName: 'Odisha',
    districtId: 'OD-KHO',
    districtName: 'Khurda (Bhubaneswar)',
    city: 'Bhubaneswar',
    address: 'Gothapatna, Malipada, Bhubaneswar - 751003',
    pincode: '751003',
    website: 'https://www.iiit-bh.ac.in',
    establishedYear: 2006,
    accreditation: 'NAAC A Grade',
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIIT Bhubaneswar', 'IIIT-BH', 'Advaita IIIT-BH'],
    studentCount: 1800,
    mentorCount: 3,
    eventCount: 12,
    ambassadorCount: 2,
    tags: ['IIIT', 'Bhubaneswar', 'Tech', 'Computer Science'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Gujarat
  {
    id: 'inst-iit-gandhinagar',
    aisheCode: 'U-0136',
    name: 'Indian Institute of Technology Gandhinagar',
    shortName: 'IIT Gandhinagar',
    slug: 'iit-gandhinagar',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'GJ',
    stateName: 'Gujarat',
    districtId: 'GJ-GAN',
    districtName: 'Gandhinagar',
    city: 'Palaj, Gandhinagar',
    address: 'Palaj, Gandhinagar - 382355',
    pincode: '382355',
    website: 'https://iitgn.ac.in',
    establishedYear: 2008,
    accreditation: 'Institute of National Importance',
    nirfRank: 18,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Gandhinagar', 'IITGN', 'Palaj IIT', 'Amalthea IITGN', 'Blithchron IITGN'],
    studentCount: 2400,
    mentorCount: 4,
    eventCount: 18,
    ambassadorCount: 3,
    tags: ['IIT', 'Central Govt', 'Palaj', 'Gandhinagar'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },
  {
    id: 'inst-svnit-surat',
    aisheCode: 'U-0149',
    name: 'Sardar Vallabhbhai National Institute of Technology Surat',
    shortName: 'SVNIT Surat',
    slug: 'svnit-surat',
    institutionType: 'INSTITUTE',
    institutionCategory: 'NIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'GJ',
    stateName: 'Gujarat',
    districtId: 'GJ-SUR',
    districtName: 'Surat',
    city: 'Surat',
    address: 'Ichchhanath, Dumas Road, Surat - 395007',
    pincode: '395007',
    website: 'https://www.svnit.ac.in',
    establishedYear: 1961,
    accreditation: 'Institute of National Importance',
    nirfRank: 65,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['SVNIT Surat', 'SVNIT', 'REC Surat', 'MindBend SVNIT', 'Sparsh SVNIT'],
    studentCount: 5200,
    mentorCount: 4,
    eventCount: 19,
    ambassadorCount: 3,
    tags: ['NIT', 'Central Govt', 'Ichchhanath', 'Surat'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  },

  // Assam / North East
  {
    id: 'inst-iit-guwahati',
    aisheCode: 'U-0053',
    name: 'Indian Institute of Technology Guwahati',
    shortName: 'IIT Guwahati',
    slug: 'iit-guwahati',
    institutionType: 'INSTITUTE',
    institutionCategory: 'IIT',
    managementType: 'CENTRAL_GOVT',
    stateId: 'AS',
    stateName: 'Assam',
    districtId: 'AS-KAM',
    districtName: 'Kamrup Metropolitan (Guwahati)',
    city: 'Amingaon, North Guwahati',
    address: 'Surjyamukhi, North Guwahati, Guwahati - 781039',
    pincode: '781039',
    website: 'https://www.iitg.ac.in',
    establishedYear: 1994,
    accreditation: 'Institute of National Importance',
    nirfRank: 7,
    verified: true,
    status: 'ACTIVE',
    searchAliases: ['IIT Guwahati', 'IITG', 'Techniche IITG', 'Alcheringa IITG', 'North Guwahati IIT'],
    studentCount: 7800,
    mentorCount: 6,
    eventCount: 30,
    ambassadorCount: 4,
    tags: ['IIT', 'Central Govt', 'Brahmaputra Campus', 'Guwahati', 'North East'],
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z'
  }
];
